version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: verdex
      POSTGRES_PASSWORD: verdex
      POSTGRES_DB: verdex
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build:
      context: apps/api
      dockerfile: ../infra/Dockerfile.api
    depends_on: [db, redis]
    ports: ["3000:3000"]
    env_file: .env

volumes:
  pgdata:
