FROM node:20-alpine AS deps
WORKDIR /app
COPY apps/mobile/package.json apps/mobile/yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:20-alpine AS builder
WORKDIR /app
COPY apps/mobile /app
COPY --from=deps /app/node_modules ./node_modules
RUN yarn build:android

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
