FROM rust:1.79 AS builder
WORKDIR /usr/src/app
COPY apps/api .
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/app/target/release/verdex-api /usr/local/bin/api
CMD ["api"]
